artifact_uri: file:D:/Bootcamp/Laskar AI/Submission/Eksperimen_SML_Tiani/Workflow-CI/MLProject/mlruns_new/0/c9fc4327473a4e43aa3e20b057ad0fe6/artifacts
end_time: 1749879869498
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: c9fc4327473a4e43aa3e20b057ad0fe6
run_name: legendary-grouse-585
source_name: ''
source_type: 4
source_version: ''
start_time: 1749879849039
status: 3
tags: []
user_id: inait
