artifact_location: file:D:/Bootcamp/Laskar AI/Submission/Eksperimen_SML_Tiani/Workflow-CI/MLProject/mlruns_new/0
creation_time: 1749879849037
experiment_id: '0'
last_update_time: 1749879849037
lifecycle_stage: active
name: Default
